language: node_js
node_js:
- '4.1'
env:
- TEST_DIR=front.web
- TEST_DIR=admin.web
script: cd $TEST_DIR && npm install && bower install && npm test
deploy:
  provider: s3
  bucket: "bodite-html"
  local_dir: build
  skip-cleanup: true
  #acl: public_read
  region: eu-west-1
  detect_encoding: true
  secret_access_key:
    secure: U5KfiRR1Bis0P013hDNSZE1MVPIaTqOQTzcL7CTi0Xg94QlBQVSepj/mwue4zye2Y+PNF4BDeVNGfFh0q+r3WdqxfD4apUD80KZg2yQCF8/GbC8iG4nLPVlCZGatq14AXn2+L4Xq6bN4vfKh8vUnn0qO5X6UsrwhHPqAbHL4kJURHlc/iWQl9VUaTPsoPdMyiG5J9mKrnvuKSwVE5EwZGDWbXPA2drEEiaoOd02FfkGuUhtqbBqwSuGGLxEa3rILFZ2mWhKVCkylwfdk9LYeWFws0bukMpVqN57bs9hVxVhL/h6mlVxCaxt/Aa2DmhzJUJBeD2cpmfc/5myYIaoV8IUJhb8oNct+VZLtqIfS1rVZZxS0sjjyMboe/997psqPO5FM4on6vXEw0hHmKAwF4ipAIqkQqt4eNY0GFvuyd5Zxkn37UJRtnAVa03KppF1ulVb015Uh8H7XZgDzZlTouRtgp3TnFHtBARE0Zx9qay/Cu13Z0H9+qKX+9JiRMHNDv9ADx+M5vMBifhokiz8hRlT1gK61CyXAcK+WUAj/AVbmJ4iXZyZet9r/8dlW8oH5L49Jph/EPW7CqzleHj5LrwaTW9x7tTsPBOg18rg7+AebHlY9P7CDMhS2LYl+HdhOYJfNgQ27WGs9aJKNKQTTEJYhEQ2ubRkNGO0vFQhypJg=
  access_key_id:
    secure: kylWmQCRvlochM3B9GUcJUQDPhzGl1+MKNE2rb5gjrie/6fGr0u2+CRRsaYcvj46/PGeKe27Yf8SiSnWDoEtdkSRrE7ElJQ55Pw1VqVlz/xJaFLbmmt49MfwGwZJ0q7R6806KvUMnM3bN0FyVVoR4Ggz/vmEpIWwa7eoZ4e3/Q4Q3/bRe+wwnr7SynpmE757uaY8tIVU9GDWpk6B5u9jic4s4+HabJLo1EQQHiaBohWrxEKdOof3fsbPUXz3suEFDqrRbw8xMs+99COM+P6dNt6z+p88Yk7UgEd5nWAtQ8pyhm6iLOBtJFmf5082Y6uiJCEhSGAcMr6da+VcKoMXLDDJjEnfnpFVUzGj2N1YbQtPBkxyl6nQL/H9KJLM22dd/hsa16MF9DcOzDVLa+ug84j0KrxkWoQIALqX6Cjf8anuI/OizLJBNk8O6W+BCVDN8y+1mEdRDOxFPyAIe83J3zmHQf0srPFWk7UqbBfY1VuwUEXbdNsSouZgDNXF6f9vh4hKdMbc/twVwdxNc++NRjq1m1seDWdJeCxxVI5JM+HxcPqMucExn+7ERknmefekdilJmaHW9NnH5qlrTZxFD5mAmTB6kOhGqyihml0x0GQWk3o5EnLsmpk4wSX8aNuND5X/IV+gzHDnHKH+Jxng4I4xW2djO8Nb3umaCE9MC6E=
